### ISSUE TITLE
Unequal contributor sizes at Read.md

### ISSUE THREAD

**Issue by JohnPatrickAncajas** [MrAshwin2142/OpenQuotes#30]
**Describe the bug**
The sizes of the cell and images for each contributors is unequal at the Read.md, specifically the images making it look a bit off.

**To Reproduce**
1. Go to either Read.md or scroll to it from repository home.
2. See error.

**Expected behavior**
The sizes of the cell and images will not be equal although assuming from the code, they are made to be.

**Screenshots**
![Screenshot_2023-11-01-21-02-09-21.jpg](https://github.com/MrAshwin2142/OpenQuotes/assets/143093214/c2fe7ea5-f69e-453f-b271-ad02dd55906e)

![Screenshot_2023-11-01-14-06-35-85.jpg](https://github.com/MrAshwin2142/OpenQuotes/assets/143093214/89477249-73bf-454c-ae65-25e497e31d2a)

![Screenshot_2023-11-01-21-09-52-62.jpg](https://github.com/MrAshwin2142/OpenQuotes/assets/143093214/0be6978c-81ea-42d3-99a6-581b3b3586e2)

**Desktop (please complete the following information):**
 - OS: [NA]
 - Browser [NA]
 - Version [NA]

**Smartphone (please complete the following information):**
 - Device: [OPPO A5s]
 - OS: [V5.2.1]
 - Browser [Chrome]
 - Version [Chrome 118.0.5993.111]

**Additional context**
![Screenshot_2023-11-01-14-21-17-62.jpg](https://github.com/MrAshwin2142/OpenQuotes/assets/143093214/3c805062-26c5-4b1e-bb50-0780deb625ae)

![Screenshot_2023-11-01-14-22-21-67.jpg](https://github.com/MrAshwin2142/OpenQuotes/assets/143093214/83a61ba0-8aeb-4a27-8ba3-472cb75bea22)

I did some test and the width of the image and cell seems to be affected by the length of the text bellow it and not the declared value in the code.

**Comment by MrAshwin2142** [comment]
The contributor list is added by all-contributors [bot]. image size looks strange sometimes but its default styling provided by the bot.

**Comment by JohnPatrickAncajas** [comment]
Gotcha! I'll just let that be then
