### ISSUE TITLE
Change Quote Display Method to Randomize Quotes

### ISSUE THREAD

**Issue by MrAshwin2142** [MrAshwin2142/OpenQuotes#32]
Hello, OpenQuotes community! 👋

We're considering an improvement to the way quotes are displayed on the OpenQuotes platform. Currently, quotes cycle in a specific order, but we believe introducing randomness can make the experience more exciting and refreshing for our users.

### Issue Details:

**Task:** The task is to modify the project's code to display random quotes on the page. Each time a user visits or refreshes the page, they will see a different quote, enhancing the variety and appeal.

**Contributor-Friendly**: This issue is ideal for those interested in front-end development and adding a dynamic touch to the project.

Join us in making OpenQuotes a platform where every visit brings a fresh burst of inspiration. If you have questions or need guidance, please feel free to reach out.

**Comment by pheb2014939ctu** [comment]
I'm about to submit the Pull Request for this task now. @MrAshwin2142

**Comment by JohnPatrickAncajas** [comment]
Hello Sir @MrAshwin2142! I noticed the JavaScript for the image swap was in the HTML file. Can I move them to the main.js instead to improve it? Thank you!

**Comment by MrAshwin2142** [comment]
Thank you @pheb2014939ctu
