### ISSUE TITLE
Make Page Mobile Responsive

### ISSUE THREAD

**Issue by MrAshwin2142** [MrAshwin2142/OpenQuotes#4]
Hello everyone! 👋

As we continue to improve the OpenQuotes project, one of our next objectives is to enhance the mobile user experience by making our page fully responsive. This will ensure that our content looks great and is easy to access on a variety of mobile devices.

### Responsiveness: 
The objective is to create a responsive design for the OpenQuotes page, making it user-friendly on smartphones and tablets. This includes optimizing the layout, font sizes, and images for smaller screens.

### How to Get Started:

- Fork the OpenQuotes repository if you haven't already.
- Work on the necessary CSS and HTML changes to achieve mobile responsiveness.
- Submit a pull request to share your improvements with the community.

### Contributor-Friendly:
 This issue is ideal for contributors who are interested in frontend development and want to dive into creating responsive designs. It's an excellent opportunity to start your open source journey or further develop your skills.

Let's come together to make OpenQuotes accessible to a wider audience by ensuring it's mobile-responsive. If you have any questions or need assistance, don't hesitate to reach out. We appreciate your contributions and look forward to making OpenQuotes an even better platform for inspiration! 🌟📱

**Comment by devraushan** [comment]
I'm Intrested to work on this one

**Comment by MrAshwin2142** [comment]
Thank you, @devraushan , for your contribution! 🙌 This task is now completed, and we appreciate your effort. We're closing this issue. If you have more to share or work on, feel free to open new ones. 🚀
