### ISSUE TITLE
Text Overlapping Issue on Mobile

### ISSUE THREAD

**Issue by MrAshwin2142** [MrAshwin2142/OpenQuotes#7]
Hello everyone! 👋

We've identified a bug in the OpenQuotes project where text is overlapping on mobile devices, affecting the user experience. We're looking for assistance in resolving this issue to ensure a seamless experience for our mobile users.

### Issue Details:

**Problem**: Text is currently overlapping on the mobile version of the OpenQuotes page, making it difficult to read and navigate.
How to Reproduce:

Open the OpenQuotes project on a mobile device (e.g., smartphone or tablet).

Navigate to [specific page or section where the issue occurs].

Observe the text overlapping issue.

### Expected Behavior:

Text should be displayed clearly and should not overlap.

### How to Get Started:

- Fork the OpenQuotes repository if you haven't already.
- Work on resolving the text overlapping issue on the mobile version of the project.
- Submit a pull request to share your solution with the community.

**Contributor-Friendly**: This bug report is suitable for contributors interested in UI and mobile responsiveness.

Join us in fixing this issue to ensure that our mobile users have an optimal experience. If you have any questions or ideas for a solution, please feel free to reach out. We appreciate your contributions and look forward to making OpenQuotes even better for all users! 🌟📱

**Comment by devraushan** [comment]
sir can you share screenshot of the bug bcs I'm unable to reproduce in my device

**Comment by MrAshwin2142** [comment]
![Screenshot 2023-10-31 121837](https://github.com/MrAshwin2142/OpenQuotes/assets/89156541/f8b74199-724e-431b-9e92-b76da6a96b1c)

**Comment by devraushan** [comment]
Thank you sir I'm trying to fix this one

**Comment by YeiHuynh** [comment]
Hi, I am working on this issue. Could you please assign it to me?

**Comment by diemmee** [comment]
.take

**Comment by MrAshwin2142** [comment]
Hello @YeiHuynh  and @diemmee,

Just a quick update on the issue you were interested in. @devraushan  is currently working on it. Thanks for your willingness to contribute! 😊

If you'd like to help with another issue, or if you have any new ideas, feel free to explore the list of available issues. Your contributions are greatly appreciated.

**Comment by YeiHuynh** [comment]
> Hello @YeiHuynh and @diemmee,
> 
> Just a quick update on the issue you were interested in. @devraushan is currently working on it. Thanks for your willingness to contribute! 😊
> 
> If you'd like to help with another issue, or if you have any new ideas, feel free to explore the list of available issues. Your contributions are greatly appreciated.

Thank sir

**Comment by JohnPatrickAncajas** [comment]
Hello! I just wanted to say that I think the part I added might have also fixed this bug sir @MrAshwin2142.

**Comment by MrAshwin2142** [comment]
Thank you again @JohnPatrickAncajas now it working fine
